### CREATE five documents.
POST http://localhost:3000/games HTTP/1.1
content-type: application/json

{
    "title": "Star Wars Jedi:Survivor",
    "timeToBeat": 30,
    "releaseDate": "04-03-2023"
}


### CREATE 2
POST http://localhost:3000/games HTTP/1.1
content-type: application/json

{
     "title": "Alan Wake Remastered",
    "timeToBeat": 12,
    "releaseDate": "03-14-2023"
}

### CREATE 3
POST http://localhost:3000/games HTTP/1.1
content-type: application/json

{
     "title": "Hifi Rush",
    "timeToBeat": 10,
    "releaseDate": "04-17-2023"
}

### CREATE 4
POST http://localhost:3000/games HTTP/1.1
content-type: application/json

{
    "title": "Destiny 2",
    "timeToBeat": 100,
    "releaseDate": "02-12-2020"
}

### CREATE 5
POST http://localhost:3000/games HTTP/1.1
content-type: application/json

{
   "title": "Dead Space",
    "timeToBeat": 22,
    "releaseDate": "01-03-2023"
}


### RETRIEVE all documents.
GET http://localhost:3000/movies HTTP/1.1



### RETRIEVE a document by its ID.
### Replace the following ID with one that exists in the collection.
GET http://localhost:3000/movies/63fe46f07cdabdac528b7ee3 HTTP/1.1


### UPDATE one document's year, by ID.
### Replace the id in the following request with one that exists
### and update the title, year, and/or language:
PUT http://localhost:3000/movies/63fe444e0dd596fe1eaaaec1 HTTP/1.1
content-type: application/json

{
    "title": "Sorry to Bother You",
    "year": 2016,
    "language": "English"
}

### DELETE by ID (no response provided)
DELETE http://localhost:3000/movies/63fe444e0dd596fe1eaaaec1 HTTP/1.1


### DELETEs ALL documents!
DELETE http://localhost:3000/movies/ HTTP/1.1

